
namespace OpenAI
{
	[default_interface]
	runtimeclass OpenAiOptions
	{
		OpenAiOptions();
	};

	[default_interface]
	runtimeclass OpenAiService
	{
		OpenAiService();

		Boolean IsRunning{ get; };

		void SetOpenAiSecretKey(String key);
		Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IBuffer> GenerateDalleImageAsync(String keywords);
		Windows.Foundation.IAsyncOperation<Windows.Storage.Streams.IBuffer> GenerateDalleVariantAsync(Windows.Storage.StorageFile file);
	}
}

// OpenAI Image
namespace OpenAI.Image
{
	enum SizeType
	{
		Size1024
	};

	unsealed runtimeclass ImageRequest
	{
		String Prompt{ get; set; };
		Int32 CreationNumber{ get; set; };
		String ImageName{ get; set; };
		SizeType Size{ get; set; };
		Boolean IsValid{ get; };
	};

	[default_interface]
	runtimeclass ImageCreateRequest : ImageRequest
	{
		ImageCreateRequest();
	};

	[default_interface]
	runtimeclass ImageVariationRequest : ImageRequest
	{
		ImageVariationRequest();
	};

	[default_interface]
	runtimeclass ImageEditRequest : ImageRequest
	{
		ImageEditRequest();
	};

	unsealed runtimeclass ImageResponse
	{
		protected ImageResponse();

		Boolean IsResponseSuccess{ get; };
	};
}
